version: "3"
services:
  monapp:
    build: .
    image: performance
    depends_on:
      - rewardmicroservice
    ports:
      - "8080:8080"
  rewardmicroservice:
    build: ../../RewardIsolation/TourGuide
    image: rewardmicroservice
    ports:
      - "9002:9002"